services:
  postgres:
    image: postgres:17
    container_name: fallboot-postgres-dev
    environment:
      POSTGRES_DB: fallboot
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: password1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: