spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fallboot
    username: myUser
    password: password1234
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_W61ZUEYKp
